# Generated by Django 3.2.6 on 2022-03-05 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0003_auto_20220306_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilefeeditem',
            name='tags',
        ),
        migrations.AddField(
            model_name='profilefeeditem',
            name='tags',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
