# Generated by Django 3.2.6 on 2022-03-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0004_auto_20220306_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefeeditem',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
